# instalare el workload identity segun esto https://github.com/google-github-actions/auth#setup

# This is a basic workflow to help you get started with Actions

name: CI_cd_dataflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_docker_image3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3  
    
      - name: 'gcp auth with workload'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/760721552379/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'service-account-ci-cd-github@rosy-zoo-390619.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      #- name: 'build docker image'
      #  run: 'docker build -t local_image:latest -f itd-saptm-apachebeam_v2/Dockerfile itd-saptm-apachebeam_v2'

      - name: 'print creds file'
        run: ls -lh /home/runner/work/globant_tests_dataflow/globant_tests_dataflow/

      #- name: 'docker auth'
      #  run: gcloud auth configure-docker --quiet
      
      - name: 'push image to gcr'
        run: |
           docker tag local_image:latest gcr.io/rosy-zoo-390619/gitlab_test/image_from_github:latest
           gcloud docker -- push gcr.io/rosy-zoo-390619/gitlab_test/image_from_github:lates
          
      #- name: 'docker push'
      #  run: |
      #    docker tag local_image:latest gcr.io/rosy-zoo-390619/gitlab_test/image_from_github:latest
      #    docker push gcr.io/rosy-zoo-390619/gitlab_test/image_from_github:latest

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: make ls master
        run: ls
        
      - name: make pwd master
        run: pwd

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
